AllCops:
  Include:
    - "**/Rakefile"
    - "**/config.ru"
  Exclude:
    - "Gemfile"
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"

Style/BlockDelimiters:
  EnforcedStyle: line_count_based

Metrics/LineLength:
  Max: 80

Style/NegatedWhile:
  Enabled: false

Style/NonNilCheck:
  IncludeSemanticChanges: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: true

Style/NegatedIf:
  Enabled: false

#### Linting

Lint/AssignmentInCondition:
  Enabled: false
